### ISSUE TITLE
HDMI not working

### ISSUE THREAD

**Issue by spunkedy** [nerves-project/nerves_system_mangopi_mq_pro#7]
I figured creating an issue with documentation might be helpful.

It looks like more [people](https://www.reddit.com/r/RISCV/comments/v9q03g/looking_for_a_working_os_image_for_the_mangopi/) are having issues with the same thing.

resources:
* [armbian](https://www.reddit.com/r/RISCV/comments/v9q03g/looking_for_a_working_os_image_for_the_mangopi/)
* [details of armbian](https://forum.armbian.com/topic/21465-armbian-image-and-build-support-for-risc-v/)
* [possible config that supports hdmi](https://github.com/150balbes/build/blob/risc-v/config/boards/nezha.conf)
* [armbian kernel config?](https://github.com/150balbes/build/blob/risc-v/config/kernel/linux-d1-current.config)
* [tina defconfig](https://github.com/mangopi-sbc/Tina_d1x_append/blob/master/target/allwinner/d1-h-mq_pro/defconfig#L2349)

**Comment by spunkedy** [comment]
it initially not showing up for console might be related to uboot.

https://community.nxp.com/t5/i-MX-Processors/How-to-config-the-hdmi-with-uboot/td-p/359302

When plugging in the hdmi I see messages like:

```
[    1.036671] sun4i-drm display-engine: Adding to iommu group 0
[    1.082987] sun4i-drm display-engine: bound 5100000.mixer (ops 0xffffffff80c4d3d8)
[    1.092756] sun4i-drm display-engine: bound 5200000.mixer (ops 0xffffffff80c4d3d8)
[    1.101017] sun4i-drm display-engine: bound 5460000.tcon-top (ops 0xffffffff80c51a50)
[    1.109615] sun4i-drm display-engine: No panel or bridge found... RGB output disabled
[    1.117511] sun4i-drm display-engine: bound 5461000.lcd-controller (ops 0xffffffff80c4a488)
[    1.126299] sun4i-drm display-engine: bound 5470000.lcd-controller (ops 0xffffffff80c4a488)
[    1.135407] sun8i-dw-hdmi 5500000.hdmi: Detected HDMI TX controller v2.12a with HDCP (sun8i_dw_hdmi_phy)
[    1.145636] sun8i-dw-hdmi 5500000.hdmi: registered DesignWare HDMI I2C bus driver
[    1.153781] sun4i-drm display-engine: bound 5500000.hdmi (ops 0xffffffff80c4c4c8)
[    1.162384] [drm] Initialized sun4i-drm 1.0.0 20150629 for display-engine on minor 0
[    1.323515] fbcon: Deferring console take-over
[    1.328027] sun4i-drm display-engine: [drm] fb0: sun4i-drmdrmfb frame buffer device
[    1.341923] input: 2009800.keys as /devices/platform/soc/2009800.keys/input/input0
[    3.177525] enter sun20i_d1_hdmi_phy_config
[    3.181790] enter sun20i_d1_hdmi_phy_enable
[    3.186013] [sun20i_d1_hdmi_phy_enable]:phy_rcalend2d_status
[    3.191707] [sun20i_d1_hdmi_phy_enable]:pll_lock_status
[    3.196964] [sun20i_d1_hdmi_phy_enable]:tx_ready_status
```

**Comment by Lucassifoni** [comment]
Hi @spunkedy, just to let you know that this has been solved in a08d2c
